export { Base64Url } from "./base64-url.js";

export {
  AuthenticatorAttachment,
  AuthenticatorTransport,
  AttestationConveyancePreference,
  CoseAlgorithmIdentifier,
  CredentialMediationRequirement,
  CredentialType,
  PublicKeyCredentialHint,
  ResidentKeyRequirement,
  UserVerificationRequirement,
  WebAuthnClientCapability,
} from "./values.js";

export {
  type AllAcceptedCredentialsOptions,
  type AuthenticatorSelectionCriteria,
  type AuthenticationExtensionsClientInputs,
  type CredentialCreationSettings,
  type CredentialRequestSettings,
  type CurrentUserDetailsOptions,
  type CredentialCreationOptions,
  type CredentialRequestOptions,
  type PublicKeyCredentialCreationOptions,
  type PublicKeyCredentialCreationOptionsOverrides,
  type PublicKeyCredentialDescriptor,
  type PublicKeyCredentialParameters,
  type PublicKeyCredentialRequestOptions,
  type PublicKeyCredentialRequestOptionsOverrides,
  type PublicKeyCredentialRpEntity,
  type PublicKeyCredentialUserEntity,
  type UnknownCredentialOptions,
  authenticatorSelectionCriteria,
  credentialCreationOptions,
  credentialRequestOptions,
  publicKeyCredentialCreationOptions,
  publicKeyCredentialDescriptor,
  publicKeyCredentialParameters,
  publicKeyCredentialRequestOptions,
  publicKeyCredentialRpEntity,
  publicKeyCredentialUserEntity,
} from "./facades.js";

export type {
  AuthenticationCredential,
  AuthenticationResponse,
  PublicKeyCredentialCreationOptionsJSON,
  PublicKeyCredentialDescriptorJSON,
  PublicKeyCredentialParametersJSON,
  PublicKeyCredentialRequestOptionsJSON,
  PublicKeyCredentialRpEntityJSON,
  PublicKeyCredentialUserEntityJSON,
  RegistrationCredential,
  RegistrationResponse,
  WebAuthnCredentialPayload,
} from "./codecs.js";

export {
  WebAuthnCodecs,
  authenticationCredential,
  credentialPayloadToJson,
  credentialToJson,
  creationOptionsFromJson,
  registrationCredential,
  requestOptionsFromJson,
} from "./codecs.js";

export {
  WebAuthn,
  authenticate,
  authenticateJson,
  authenticateJsonPromise,
  authenticatePromise,
  clientCapabilities,
  clientCapabilitiesPromise,
  isAvailable,
  isConditionalMediationAvailable,
  isConditionalMediationAvailablePromise,
  isSupported,
  isUserVerifyingPlatformAuthenticatorAvailable,
  isUserVerifyingPlatformAuthenticatorAvailablePromise,
  register,
  registerJson,
  registerJsonPromise,
  registerPromise,
  signalAllAcceptedCredentials,
  signalAllAcceptedCredentialsPromise,
  signalCurrentUserDetails,
  signalCurrentUserDetailsPromise,
  signalUnknownCredential,
  signalUnknownCredentialPromise,
} from "./webauthn.js";
